version: "3.8"

services:
  freqtrade:
    build:
      context: .
    container_name: freqtrade
    restart: unless-stopped
    volumes:
      - ./clones/freqtrade/user_data:/freqtrade/user_data
    command: >
      trade
      --config user_data/config.json
      --strategy NeuroStrike

  hummingbot:
    image: hummingbot/hummingbot:latest
    container_name: hummingbot
    restart: unless-stopped
    volumes:
      - ~/neurogen/hb_configs:/home/hummingbot/conf
      - ~/neurogen/hb_strategies:/home/hummingbot/scripts
      - ~/neurogen/hb_logs:/home/hummingbot/logs
    tty: true
